services:
  cassandra-node:
    image: cassandra:latest
    container_name: cassandra-2
    restart: always
    network_mode: host
    environment:
      - CASSANDRA_CLUSTER_NAME=TicketCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      # !!! TU WPISZ IP TEGO KOMPUTERA (PC 2):
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.11
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      # !!! TU WPISZ IP KOMPUTERA PC 1 (Lidera):
      - CASSANDRA_SEEDS=192.168.1.10
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
