services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    restart: always
    network_mode: host # KLUCZOWE: Używamy sieci komputera
    environment:
      - CASSANDRA_CLUSTER_NAME=TicketCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      # Adres tego komputera w sieci LAN:
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.10
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      # Lista Seedów (zawsze adres PC 1):
      - CASSANDRA_SEEDS=192.168.1.10
      # Limity (jak wywali docker)
      #- MAX_HEAP_SIZE=512M
      #- HEAP_NEWSIZE=100M
